=== AliaksandrRadkevich/training2020/Evgeniy_Kokhanets/task3/src/mobileCompaniesRates/by/epam/xml/rates.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.epam.by/rates"
    xmlns:tns="http://www.epam.by/rates" elementFormDefault="qualified">
    <element name="rates">
        <complexType>
            <sequence>
                <element name="rate" maxOccurs="unbounded">
                    <complexType>
                        <sequence>
                            <element name="name" type="string" />
                            <element name="operatorName" type="string"/>
                            <element name="payroll" type="double"/>
                            <element name="callprices" minOccurs="0">
                                <complexType>
                                    <sequence>
                                        <element name="inNetwork" minOccurs="0">
                                            <simpleType >
                                                <restriction base="double">
                                                    <minInclusive value="0"/>
                                                </restriction>
                                            </simpleType>
                                        </element>
                                        <element name="outNetwork" minOccurs="0">
                                            <simpleType >
                                                <restriction base="double">
                                                    <minInclusive value="0"/>
                                                </restriction>
                                            </simpleType>
                                        </element>
                                        <element name="landline" minOccurs="0">
                                            <simpleType >
                                                <restriction base="double">
                                                    <minInclusive value="0"/>
                                                </restriction>
                                            </simpleType>
                                        </element>
                                    </sequence>
                                </complexType>
                            </element>
                            <element name="smsPrice" minOccurs="0">
                                <simpleType >
                                    <restriction base="double">
                                        <minInclusive value="0"/>
                                    </restriction>
                                </simpleType>
                            </element>
                            <element name="parameters" minOccurs="0">
                                <complexType>
                                    <sequence>
                                        <element name="favoriteNumber" type="string" minOccurs="0"/>
                                        <element name="tariffication" minOccurs="0">
                                            <simpleType>
                                                <restriction base="string">
                                                    <enumeration value="TWELVE"/>
                                                    <enumeration value="SIXTY"/>
                                                </restriction>
                                            </simpleType>
                                        </element>
                                        <element name="connectionFees" minOccurs="0">
                                            <simpleType >
                                                <restriction base="double">
                                                    <minInclusive value="0"/>
                                                </restriction>
                                            </simpleType>
                                        </element>
                                    </sequence>
                                </complexType>
                            </element>
                        </sequence>
                        <attribute name="id" type="string" use="required"/>
                    </complexType>
                </element>
            </sequence>
        </complexType>
    </element>
</schema>

=== AliaksandrRadkevich/training2020/Evgeniy_Kokhanets/task3/src/mobileCompaniesRates/by/epam/xml/rates.xml
<?xml version="1.0" encoding="UTF-8"?>
<rates xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="http://www.epam.by/rates" xsi:schemaLocation="http://www.epam.by/rates rates.xsd">
    <rate id="a87654321">
        <name>Unlimited2.0</name>
        <operatorName>MTS</operatorName>
        <payroll>15</payroll>
        <callprices>
            <inNetwork>0.1</inNetwork>
            <outNetwork>0.3</outNetwork>
            <landline>0.25</landline>
        </callprices>
        <smsPrice>0.2</smsPrice>
        <parameters>
            <favoriteNumber>+375292971705</favoriteNumber>
            <tariffication>TWELVE</tariffication>
            <connectionFees>5</connectionFees>
        </parameters>
    </rate>
    <rate id="b12345678">
        <name>Econ</name>
        <operatorName>A1</operatorName>
        <payroll>10</payroll>
        <smsPrice>0.1</smsPrice>
        <parameters>
            <favoriteNumber>+375291231251</favoriteNumber>
            <tariffication>SIXTY</tariffication>
            <connectionFees>0</connectionFees>
        </parameters>
    </rate>
</rates>
