=== AliaksandrRadkevich/training2020/Andrei_Nikalayeu/lab 3/Nikolaev_Task3_var8/airplanes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/airplanes"
	xmlns:tns="http://www.example.org/airplanes" elementFormDefault="qualified">
	<element name="airplanes">
        <complexType>
            <sequence>
                <element name="airplane" maxOccurs="unbounded">
                    <complexType>
                        <sequence>
                            <element name="model" type="string" />
                            <element name="origin" type="string" />
                            <element name="chars">
                                <complexType>
                                    <sequence>
                                        <element name="type">
                                            <simpleType>
                                                <restriction base="string">
                                                    <enumeration value="SUPPORT"/>
                                                    <enumeration value="ESCORT"/>
                                                    <enumeration value="FIGHT"/>
                                                    <enumeration value="INTERCEPT"/>
                                                    <enumeration value="SCOUT"/>
                                                </restriction>
                                            </simpleType>
                                        </element>
                                        <element name="seats">
                                            <simpleType>
                                                <restriction base="byte">
                                                    <minInclusive value="1" />
                                                    <maxInclusive value="2" />
                                                </restriction>
                                            </simpleType>
                                        </element>
                                        <element name="ammunition" minOccurs="0" maxOccurs="1">
                                            <complexType>
                                                <sequence>
                                                    <element name="gun" minOccurs="0" maxOccurs="1">
                                                        <complexType>
                                                           <attribute name="caliber">
                                                                <simpleType>
                                                                    <restriction base="positiveInteger">
                                                                        <minInclusive value="1" />
                                                                        <maxInclusive value="500" />
                                                                    </restriction>
                                                                </simpleType>
                                                            </attribute>
                                                         </complexType>
                                                    </element>
                                                    <element name="rocket" minOccurs="0" maxOccurs="1">
                                                        <complexType>
                                                            <sequence>
                                                                <element name="airToAir">
                                                                    <complexType>
                                                                        <attribute name="amount">
                                                                            <simpleType>
                                                                                <restriction base="byte">
                                                                                    <minInclusive value="1" />
                                                                                    <maxInclusive value="20" />
                                                                                </restriction>
                                                                            </simpleType>
                                                                        </attribute>
                                                                        <attribute name="range">
                                                                            <simpleType>
                                                                                <restriction base="positiveInteger">
                                                                                    <minInclusive value="1" />
                                                                                    <maxInclusive value="5000" />
                                                                                </restriction>
                                                                            </simpleType>
                                                                        </attribute>
                                                                    </complexType>
                                                                </element>
                                                                <element name="airToGrnd">
                                                                    <complexType>
                                                                        <attribute name="amount">
                                                                            <simpleType>
                                                                                <restriction base="byte">
                                                                                    <minInclusive value="1" />
                                                                                    <maxInclusive value="10" />
                                                                                </restriction>
                                                                            </simpleType>
                                                                        </attribute>
                                                                        <attribute name="height">
                                                                            <simpleType>
                                                                                <restriction base="positiveInteger">
                                                                                    <minInclusive value="1" />
                                                                                    <maxInclusive value="20000" />
                                                                                </restriction>
                                                                            </simpleType>
                                                                        </attribute>
                                                                    </complexType>
                                                                </element>
                                                            </sequence>
                                                        </complexType>
                                                    </element>
                                                </sequence>
                                            </complexType>
                                        </element>
                                        <element name="radar" minOccurs="0" maxOccurs="1">
                                            <complexType>
                                                <attribute name="name" type="string" use="required"/>
                                            </complexType>
                                        </element>
                                    </sequence>
                                </complexType>
                            </element>
                            <element name="parameters">
                                <complexType>
                                    <attribute name="length">
                                        <simpleType>
                                            <restriction base="double">
                                                <minInclusive value="1" />
                                                <maxInclusive value="45.0" />
                                            </restriction>
                                        </simpleType>
                                    </attribute>
                                    <attribute name="width">
                                        <simpleType>
                                            <restriction base="double">
                                                <minInclusive value="1" />
                                                <maxInclusive value="45.0" />
                                            </restriction>
                                        </simpleType>
                                    </attribute>
                                    <attribute name="height">
                                        <simpleType>
                                            <restriction base="double">
                                                <minInclusive value="1" />
                                                <maxInclusive value="45.0" />
                                            </restriction>
                                        </simpleType>
                                    </attribute>
                                </complexType>
                            </element>
                            <element name="price" type="positiveInteger"/>
                         </sequence>
                        <attribute name="id" type="positiveInteger" use="required"/>
                    </complexType>
                </element>
            </sequence>
        </complexType>
    </element>
</schema>

=== AliaksandrRadkevich/training2020/Andrei_Nikalayeu/lab 3/Nikolaev_Task3_var8/airplanes.xml
<?xml version="1.0" encoding="UTF-8"?>
<airplanes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xmlns="http://www.example.org/airplanes" xsi:schemaLocation="http://www.example.org/airplanes airplanes.xsd">
    <airplane id="1">
        <model>AC-130H Spectre 4</model>
        <origin>USA</origin>
        <chars>
            <type>SUPPORT</type>
            <seats>2</seats>
            <ammunition>
                <gun caliber="250"/>
                <rocket>
                    <airToAir amount="15" range="2000"/>
                    <airToGrnd amount="8" height="11000"/>
                </rocket>
            </ammunition>
            <radar name="standart"/>
        </chars>
        <parameters length="29.8" width="40.4" height="11.7"/>
        <price>10999</price>
    </airplane>
    <airplane id="2">
        <model>SU-35S</model>
        <origin>Russia</origin>
        <chars>
            <type>ESCORT</type>
            <seats>1</seats>
            <ammunition>
                <gun caliber="300"/>
            </ammunition>
            <radar name="standart"/>
        </chars>
        <parameters length="21.9" width="14.75" height="5.9"/>
        <price>19999</price>
    </airplane>
    <airplane id="3">
        <model>SU-34</model>
        <origin>Russia</origin>
        <chars>
            <type>FIGHT</type>
            <seats>2</seats>
            <ammunition>
                <gun caliber="200"/>
                <rocket>
                    <airToAir amount="20" range="3000"/>
                    <airToGrnd amount="10" height="12000"/>
                </rocket>
            </ammunition>
            <radar name="standart"/>
        </chars>
        <parameters length="23.3" width="14.7" height="6.09"/>
        <price>13499</price>
    </airplane>
    <airplane id="4">
        <model>MIG-31</model>
        <origin>USSR</origin>
        <chars>
            <type>INTERCEPT</type>
            <seats>2</seats>
            <ammunition>
                <gun caliber="250"/>
            </ammunition>
        </chars>
        <parameters length="22.7" width="13.4" height="7.19"/>
        <price>9991</price>
    </airplane>
    <airplane id="5">
        <model>Lockheed U-2</model>
        <origin>USA</origin>
        <chars>
            <type>SCOUT</type>
            <seats>1</seats>
            <radar name="standart"/>
        </chars>
        <parameters length="19.2" width="24.38" height="4.9"/>
        <price>17444</price>
    </airplane>
</airplanes>
