=== AliaksandrRadkevich/training2020/Sergej_Prudnikov/task3/stones.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.example.org/stones"
	xmlns:tns="http://www.example.org/stones"
	elementFormDefault="qualified">
	<element name="stones">
		<complexType>
			<sequence>
				<element name="stone" maxOccurs="unbounded">
					<complexType>
						<sequence>
							<element name="name" type="string" />
							<element name="preciousness">
								<simpleType>
									<restriction base="string">
										<enumeration value="PRECIOUS" />
										<enumeration value="SEMIPRECIOUS" />
									</restriction>
								</simpleType>
							</element>
							<element name="origin" type="string" />
							<element name="value" minOccurs="0">
								<simpleType>
									<restriction base="integer">
										<minExclusive value="0" />
									</restriction>
								</simpleType>
							</element>
							<element name="visual-parameters">
								<complexType>
									<sequence>
										<element name="color">
											<simpleType>
												<restriction base="string">
													<enumeration value="GREEN" />
													<enumeration value="RED" />
													<enumeration value="YELLOW" />
													<enumeration value="BLUE" />
													<enumeration value="BLACK" />
													<enumeration value="WHITE" />
												</restriction>
											</simpleType>
										</element>
										<element name="transparency">
											<simpleType>
												<restriction base="integer">
													<minExclusive value="0" />
													<maxInclusive value="100" />
												</restriction>
											</simpleType>
										</element>
										<element name="faceting">
											<simpleType>
												<restriction base="integer">
													<minExclusive value="4" />
													<maxInclusive value="15" />
												</restriction>
											</simpleType>
										</element>
									</sequence>
								</complexType>
							</element>
						</sequence>
						<attribute name="id" type="string" use="required" />
					</complexType>
				</element>
			</sequence>
		</complexType>
	</element>
</schema>

=== AliaksandrRadkevich/training2020/Sergej_Prudnikov/task3/stones.xml
<?xml version="1.0" encoding="UTF-8"?>
<stones xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="http://www.example.org/stones"
	xsi:schemaLocation="http://www.example.org/stones stones.xsd">
	<stone id="a1">
		<name>diamond</name>
		<preciousness>PRECIOUS</preciousness>
		<origin>Russia</origin>
		<value>1500</value>
		<visual-parameters>
			<color>BLUE</color>
			<transparency>90</transparency>
			<faceting>15</faceting>
		</visual-parameters>
	</stone>
	<stone id="p1">
		<name>ruby</name>
		<preciousness>PRECIOUS</preciousness>
		<origin>Thailand</origin>
		<value>23</value>
		<visual-parameters>
			<color>RED</color>
			<transparency>50</transparency>
			<faceting>12</faceting>
		</visual-parameters>
	</stone>
	<stone id="x1">
		<name>chrysolite</name>
		<preciousness>SEMIPRECIOUS</preciousness>
		<origin>Russia</origin>
		<value>15</value>
		<visual-parameters>
			<color>GREEN</color>
			<transparency>45</transparency>
			<faceting>10</faceting>
		</visual-parameters>
	</stone>
</stones>
